package checkSelenium;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class javaAlerts {
	public static void main(String args[]){
		
		// checking the popups 
		//as they are not done on selenium,some of them are not html products
		//they are called java popups
		
		WebDriver b=new FirefoxDriver();
		b.get("http://www.echoecho.com/javascript4.htm");
		b.findElement(By.xpath("html/body/div[2]/table[9]/tbody/tr/td[4]/table/tbody/tr/td/div/span/table[1]/tbody/tr/td/input[1]")).click();
		try {
			Thread.sleep(7000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();//autogenerated from excemption of treadsleep
			
			
		}
		//display if the task is done or not
		System.out.println(b.switchTo().alert().getText());
		//click on ok
		b.switchTo().alert().accept();//accept method for ok/done/or any +ve scenario
		
		
		//checking the confirmation box
		b.findElement(By.xpath("html/body/div[2]/table[9]/tbody/tr/td[4]/table/tbody/tr/td/div/span/table[1]/tbody/tr/td/input[2]")).click();
		try {
			Thread.sleep(7000);
		} catch (InterruptedException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		//display if the task is done or not
			
				//click on cancel
		System.out.println(b.switchTo().alert().getText());
				b.switchTo().alert().dismiss();//dismiss method for cancel/not ok
				
				//checking the prompt box
				
				b.findElement(By.xpath("html/body/div[2]/table[9]/tbody/tr/td[4]/table/tbody/tr/td/div/span/table[1]/tbody/tr/td/input[3]")).click();
				try {
					Thread.sleep(7000);
				} catch (InterruptedException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				//display if the task is done or not
					
						//click on text
				System.out.println(b.switchTo().alert().getText());
						b.switchTo().alert().sendKeys("harish");//enter the text using sendkeys method
						try {
							Thread.sleep(7000);
						} catch (InterruptedException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
						b.switchTo().alert().accept();
	
	}

}
